
# Program to guess the number
# developed by @digital_dimensions


import random

num= random.randint(0,10)                                                               # Generating a random number
print("Guess the number generated by the system between 0 and 10 ")
user= int(input("Enter your guess : "))                                                 # Getting input from user
bool= True
while bool:                                                                             # condition 
    if num==user:
        print(" Wow, Your guess is spot on !!")
        bool= False
    else:
        print("Sorry your guess is wrong!!")
        if num>user:
            print("Your guess is lower than the number!!")
            print("Try again")
            pass
        else:
            print("Your guess is higher than the number!!")
            print("Try again")
            pass

        user = int(input("Enter your guess : "))
        bool= True





